version: '3.8'

# Create Network for DB
networks:
    zenergy-network:
        name: zenergy-network

# Z-Energy Database Volume
volumes:
    zenergy:
        name: zenergy-volume

services:
    # MongoDB Service
    mongo:
        image: mongo:latest
        container_name: mongo
        ports:
            - 27017:27017
        networks:
            - zenergy-network
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
            - MONGO_INITDB_DB=${MONGO_INITDB_DB}
            - MONGODB_URI=${MONGODB_URI}
            - MONGO_USER=${MONGO_USER}
            - MONGO_PASS=${MONGO_PASS}
        volumes:
            - 'zenergy:/data/db'
            - './mongoinit.sh/:/docker-entrypoint-initdb.d/mongoinit.sh:ro'

    # Next JS Web Service

    web:
        container_name: web
        depends_on:
            - mongo
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - zenergy-network
        ports:
            - 3000:3000
