version: '3'
services:
    mongo:
        image: mongo:latest
        ports:
            - 27017:27017
        networks:
            - mongo-network
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=1234
        volumes:
            - './data:/data/db'

    mongo-express:
        image: mongo-express:latest
        ports:
            - 8080:8081
        restart: always
        depends_on:
            - mongo
        networks:
            - mongo-network
        volumes:
            - './data:/data/db'
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongo
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=1234
            - ME_CONFIG_MONGODB_URL=mongodb://root:1234@mongo:27017/
networks:
    mongo-network:
        name: mongo-network
